### ISSUE TITLE
Add live demo

### ISSUE THREAD

**Issue by mtekman** [mtekman/org-tanglesync.el#1]
![ezgif-2-f2d9f13ff3a6](https://user-images.githubusercontent.com/20641402/63469413-7335e480-c46a-11e9-8a00-1825676f3b2d.gif)

**Comment by mtekman** [comment]
![test](https://user-images.githubusercontent.com/20641402/71929804-b59e5a80-319a-11ea-83d5-20f4343f08ea.gif)

**Comment by mtekman** [comment]
Method:

```bash
recordmydesktop --windowid 0x160013f --no-sound
ffmpeg -i out-1.ogv -ss 1 -t 43 test.gif
```

**Comment by mtekman** [comment]
as per alphapapa request, I've sped up the screencast a little.

![together](https://user-images.githubusercontent.com/20641402/72068928-6107f600-32e6-11ea-88e7-29bf43a32faf.gif)

**Comment by alphapapa** [comment]
That is a big improvement.  :)

BTW, here's a tool that makes recording screencasts easy: https://github.com/alphapapa/bashcaster

But for recording within Emacs (i.e. when you're only showing Emacs), you should generally use `gif-screencast`.  It's on MELPA.  Here's an example of a script I wrote to perform a demo in Emacs (I got tired of re-enacting the sequence of events): https://github.com/alphapapa/org-ql/blob/master/images/demo-helm-org-ql.sh

See also https://github.com/alphapapa/emacs-package-dev-handbook#animations--screencasts

**Comment by mtekman** [comment]
wow nice, I just gave them a go -- definitely much smaller sizes and better quality.

I really do like the one-action-one-screenshot ethos

**Comment by mtekman** [comment]
Added gif-screencast

![output22](https://user-images.githubusercontent.com/20641402/72112550-2d58ba80-333e-11ea-9616-1d9d5e7df947.gif)

```bash
#!/bin/bash

wid=0xa0013f
type="xdotool type --window $wid --delay 70"
quick="xdotool type --window $wid --delay 10"
press="xdotool key --window $wid"

xdotool key "Hyper_L+Up"
$press "ctrl+F9"
sleep 4
$press "Return"
$press "Up"
$type "I can write into the ~/.xinitrc file in this buffer here,"
$press "Return"
sleep 0.1
$type "and when I save my changes,"
sleep 0.2
$type " they will be synced back into"
$press "Return"
$type "the tangled src block in the original org buffer."
$press "Return"; $type "3"; sleep 0.7;
$press "space"; $type "2"; sleep 0.7;
$press "space"; $type "1"; sleep 0.7;
$press "space"; $quick ": C-x C-s";
$press "ctrl+x"; $press "ctrl+s";
$press "space"; $press "BackSpace";
$press "ctrl+x"; $press "ctrl+s";
sleep 3
$press "ctrl+space"
$press "ctrl+a"; sleep 0.5;
$press "Up"; sleep 0.1;
$press "Up"; sleep 0.2;
$press "Up"; sleep 0.1;
$press "Delete";
$press "Delete";
sleep 0.5
$press "ctrl+x"; $press "ctrl+s";
$press "space"; $press "BackSpace";
$press "ctrl+x"; $press "ctrl+s";
sleep 2
$type "pretty neat,"; sleep 0.1; $type " huh."
$press "Return";
$press "ctrl+x"; $press "ctrl+s";
$press "space"; $press "BackSpace";
$press "ctrl+x"; $press "ctrl+s";
sleep 2
$press "F9"
```
