### ISSUE TITLE
Executable dotfile

### ISSUE THREAD

**Issue by arkhan3x** [mtekman/org-tanglesync.el#11]
Greetings, excellent work.

I am migrating my dotfiles to org-tanglesync, but there was a question about how execution attributes can be assigned to a file .?

For example, I have this file that I want to put in $ HOME/.bin
```sh
#!/bin/sh
command="rofi -width 15 -run-command \"xonsh -i -c '{cmd}'\" -show run"

[[ -d "$HOME/.bin" ]] && PATH=$HOME/.bin:$PATH eval $command || eval $command
```
, and so I can add it to my user's $PATH I need that file to be executable.

How can I do it..?

Thank you

**Comment by mtekman** [comment]
>  am migrating my dotfiles to org-tanglesync

org-mode ;-)  org-tanglesync is just a package I wrote for it.

> how execution attributes can be assigned to a file

well to make it executable just add `:tangle-mode (identity #o755)`  to your [block headers](https://orgmode.org/manual/tangle_002dmode.html), or add `#+PROPERTY:   header-args+ :tangle-mode (identity #o755)` to the top of your org file if you want all your blocks to be executable.

See my conf for other ideas: https://gist.github.com/mtekman/5f885e99ebabc6c68f85790581eceb02

********

```org
#+BEGIN_SRC sh :tangle ~/mycustomrofi.source :tangle-mode (identity #0755)
    #!/bin/sh
    command="rofi -width 15 -run-command \"xonsh -i -c '{cmd}'\" -show run"

    [[ -d "$HOME/.bin" ]] && PATH=$HOME/.bin:$PATH eval $command || eval $command
  #+END_SRC
```
and then in your .profile (or your .bash_profile, or .zprofile)

```org
  #+BEGIN_SRC sh :tangle ~/.profile
    source $HOME/mycustomrofi.source
  #+END_SRC
```

So for your specific problem, I would put your code into an org src block and give it a tangle filename (and execution mode). Then I would tell my .profile (which gets sourced automatically by the shell) to source the tangled filename.

If these tangled filenames dont exist, then you need to export them first (via `C-c C-v t` ).

**Comment by arkhan3x** [comment]
great thank you very much
