### ISSUE TITLE
Writing tangled file doesn't update org file

### ISSUE THREAD

**Issue by dimt** [mtekman/org-tanglesync.el#16]
Pushing changes from the tangled file back to the org block doesn't seem to work in my case.
When I evaluate `(org-tanglesync-watch-make-watchlist org-tanglesync-watch-files)`, it works as expected but when I run `describe-variable` on org-tanglesync-confmap there is no mapping between my org and tangled file.

I recorded changing the tangled file and then saving, as well as evaluating the two commands.
My org-tanglesync config is on the right window.

![screencast](https://user-images.githubusercontent.com/13005435/94963623-1d52bd80-0501-11eb-9696-153c2de3a6ba.gif)

**Comment by mtekman** [comment]
Hi, thanks for the report

* Is `org-tanglesync-mode` enabled?
* Does it work if you set `org-tanglesync-watch-files` to just "test.org" ?
* Does it work if you also set the `:tangle test.el` to `:tangle /absolute/path/to/test.el` ?

Cheers!

**Comment by dimt** [comment]
> Hi, thanks for the report
> 
>     * Is `org-tanglesync-mode` enabled?
> 
>     * Does it work if you set `org-tanglesync-watch-files` to just "test.org" ?
> 
>     * Does it work if you also set the `:tangle test.el` to `:tangle /absolute/path/to/test.el` ?
> 
> 
> Cheers!

Hi,

Yes `org-tanglesync-mode` is enabled. Unfortunately it isn't visible due to `keycast-mode`.
I tried using relative and absolute paths for each file without success.

**Comment by mtekman** [comment]
Hmm... what version of emacs are you using?

**Comment by dimt** [comment]
GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3)

**Comment by mtekman** [comment]
Is there another `test.el` block within your org file?

**Comment by dimt** [comment]
No, there is no other `test.el` block.

However, evaluating `(setq org-tanglesync-confmap (org-tanglesync-watch-make-watchlist org-tanglesync-watch-files))` fixes the problem.

**Comment by dimt** [comment]
My elisp knowledge is very limited.
Is there a better solution than evaluating this expression in every elisp file I want to sync?

**Comment by mtekman** [comment]
oh whoops, its been a while since I looked at the source -- does it work if you enable `org-tanglesync-watch-mode` instead?

**Comment by dimt** [comment]
It is enabled when I open any file thanks to this hook: `((prog-mode text-mode) . org-tanglesync-watch-mode))`, but it still doesn't sync to the org block.

**Comment by dimt** [comment]
This is embarrassing. Full path to org file was wrong. 
It works fine using full path.
