### ISSUE TITLE
Readme should teach people about `tangle-mode` option

### ISSUE THREAD

**Issue by mankoff** [mtekman/org-tanglesync.el#2]
This is a good package. But to help people avoid this conflict, your README should teach people about tangle options `:comments link :tangle-mode (identity #o444)` which makes the tangled files read-only and provides links back to the source. This significantly reduces the chance of editing the tangled file by mistake, instead of the Org source.

**Comment by mtekman** [comment]
Thanks @mankoff! I added a commentary section to the README. Is that okay?
