### ISSUE TITLE
org-tanglesync-user-edit-buffer not fired up when the source code block is being edited

### ISSUE THREAD

**Issue by BonfaceKilz** [mtekman/org-tanglesync.el#5]
I have a src code block like this:
```
#+NAME: snake.py
#+BEGIN_SRC python :tangle /home/bonface/SideProjects/python_curses_games/games/snake.py
#+END_SRC
```

From the README, I expect that when I hit `C-c '`, I'll be prompted to pull the external changes... but nothing happens. Could you help me out? This is a really nice feature for literate programming which I do a lot

**Comment by mtekman** [comment]
Hey thanks for finding this -- it looks like I did not have a handler for tangled files that either do not exist yet, or are blank blocks.

So I just pushed an update [just now](https://github.com/mtekman/org-tanglesync.el/commit/9e6f074bae1ce7579f495b62fc6ee08f47b63e95), which should be merged into melpa on their next build (tomorrow, I think?), so you would need to reinstall the package when it does.

This update now has provided two contingencies in the user-edit-mode:
  * If the block is blank and the external file exists, pull external changes
  * If the block is blank and the external file does not exist, then a message is given to the user that they need to edit the block first and then export.

Can you try this out (either by cloning the repo, or waiting for the melpa build tomorrow) and let me know if it works for you?

**Comment by BonfaceKilz** [comment]
Just tested it and it works like a charm. +1 for the really quick fix. Thanks a bunch! I'm going ahead to close this now.
