### ISSUE TITLE
Bug: org-tanglesync-user-edit-buffer: Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by BonfaceKilz** [mtekman/org-tanglesync.el#6]
Steps to reproduce:
- Have an src block which does not have `:tangle`:
```
#+begin_src sh
#+end_src
```
- Hit `C '`. On the *Messages* buffer you will get: `org-tanglesync-user-edit-buffer: Wrong type argument: stringp, nil`. When you exit the `edit buffer` you can no longer edit the src block. You'll get this error: `user-error: Cannot modify an area being edited in a dedicated buffer`

@mtekman I think you should add a check for seeing whether the `:tangle` property exists. I don't know enough elisp to do this, but I can try to hack around something after work.

**Comment by BonfaceKilz** [comment]
@mtekman here's a proposed solution that I've hacked around: https://github.com/mtekman/org-tanglesync.el/pull/7/commits/2c5eb0a1c97672110819f830d3b30bb83426e4cc

Could you check it out?

**Comment by mtekman** [comment]
`user-error: Cannot modify an area being edited in a dedicated buffer`, yep I see this too from time to time and I do not yet know how to reproduce it explicitly.

I think it has to do with edit hook not sending the right signal back after execution that the block is no longer being modified, but I need to dig more into the org internals to see how this is being done natively.

**Comment by mtekman** [comment]
Okay, I just pushed a fix that should stop the hanging uneditable buffer issue

https://github.com/mtekman/org-tanglesync.el/commit/d99181f173b4e55b4e835d99fcd415e62beb047f

Please try it and let me know if it resolves the issue

**Comment by BonfaceKilz** [comment]
You don't need to dig into org internals. The bug happens when you have the `:tangle` property missing in the src block header. I'll check out your commit when I arrive home. In the meantime, to reproduce the bug, remove the tangle property from your header and hit `C-c '`. Check out the solution from the PR I submitted. That fixes the problem IMO

**Comment by BonfaceKilz** [comment]
I've just seen your comment on the PR. I'll respond to it once I'm close to a machine.

**Comment by BonfaceKilz** [comment]
@mtekman I've just tested the new fix and it works just fine. It's way less hacky than what I had. Thanks for spinning that up in such a short time!
